# Generated by Django 4.2.7 on 2023-12-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="newspaper",
            name="additional_topics",
            field=models.ManyToManyField(related_name="topics", to="newspaper.topic"),
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subjects",
                to="newspaper.topic",
            ),
        ),
    ]
