# Generated by Django 4.2.7 on 2023-12-05 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0002_alter_topic_options_newspaper_additional_topics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="newspapers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
