# Generated by Django 4.2.7 on 2023-12-06 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0003_alter_newspaper_publishers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="newspaper_redactors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
